# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
tiles = Tile.create(
		[
			{ name: 'tile-00', count: 0},
			{ name: 'tile-01', count: 0},
			{ name: 'tile-02', count: 0},
			{ name: 'tile-03', count: 0},
			{ name: 'tile-04', count: 0},
			{ name: 'tile-05', count: 0},
			{ name: 'tile-06', count: 0},
			{ name: 'tile-07', count: 0},
			{ name: 'tile-08', count: 0},
			{ name: 'tile-09', count: 0},
			{ name: 'tile-10', count: 0},
			{ name: 'tile-11', count: 0},
			{ name: 'tile-12', count: 0},
			{ name: 'tile-13', count: 0},
			{ name: 'tile-14', count: 0},
			{ name: 'tile-15', count: 0},
			{ name: 'tile-16', count: 0},
			{ name: 'tile-17', count: 0},
			{ name: 'tile-18', count: 0},
			{ name: 'tile-19', count: 0},
			{ name: 'tile-20', count: 0},
			{ name: 'tile-21', count: 0},
			{ name: 'tile-22', count: 0},
			{ name: 'tile-23', count: 0},
			{ name: 'tile-24', count: 0},
			{ name: 'tile-25', count: 0},
			{ name: 'tile-26', count: 0},
			{ name: 'tile-27', count: 0},
			{ name: 'tile-28', count: 0},
			{ name: 'tile-29', count: 0},
			{ name: 'tile-30', count: 0},
			{ name: 'tile-31', count: 0},
			{ name: 'tile-32', count: 0},
			{ name: 'tile-33', count: 0},
			{ name: 'tile-34', count: 0},
			{ name: 'tile-35', count: 0},
			{ name: 'tile-36', count: 0},
			{ name: 'tile-37', count: 0},
			{ name: 'tile-38', count: 0},
			{ name: 'tile-39', count: 0},
			{ name: 'tile-40', count: 0},
			{ name: 'tile-41', count: 0},
			{ name: 'tile-42', count: 0},
			{ name: 'tile-43', count: 0},
			{ name: 'tile-44', count: 0},
			{ name: 'tile-45', count: 0},
			{ name: 'tile-46', count: 0},
			{ name: 'tile-47', count: 0},
			{ name: 'tile-48', count: 0},
			{ name: 'tile-49', count: 0},
			{ name: 'tile-50', count: 0},
			{ name: 'tile-51', count: 0},
			{ name: 'tile-52', count: 0},
			{ name: 'tile-53', count: 0},
			{ name: 'tile-54', count: 0},
			{ name: 'tile-55', count: 0},
			{ name: 'tile-56', count: 0},
			{ name: 'tile-57', count: 0},
			{ name: 'tile-58', count: 0},
			{ name: 'tile-59', count: 0},
			{ name: 'tile-60', count: 0},
			{ name: 'tile-61', count: 0},
			{ name: 'tile-62', count: 0},
			{ name: 'tile-63', count: 0}
		]
	)
